controllers:
    resource: ../src/Controller/
    type: attribute
# index:
#     path: /home
#     controller: App\Controller\TaskController::home   
    
     

# index2:
#     path: /about
#     controller: App\Controller\TaskController::about        
